version: '2.2'
services:
  web:
    build: .
    command: npm run server
    env_file: .env.loc

  web_master:
    extends: web
    image: coinspace_web
    ports:
      - '${PORT:-8080}:${PORT:-8080}'
    environment:
      MASTER: 1
